#include<iostream>
#include<vector>
#include<algorithm>

struct GenerateRandomNumbers
{
  int maxValue;
  GenerateRandomNumbers(int num)
    : maxValue(num)
  { }

  int operator()() {
    return rand() % maxValue;
  }
};


int main()
{

  std::vector<int> randomNum(10);

  //generate random numbers using lambda function
  std::generate(randomNum.begin() , randomNum.end() , []() {
                                          return rand() %100;
                                          });

  std::cout << "Random Number Generated by Lambda Function" << std::endl;
    for (int val : randomNum)
      std::cout << val << " " << std::endl;

  //generate random numbers using functors
  std::generate(randomNum.begin(), randomNum.end() , GenerateRandomNumbers(500));
  
  std::cout << "Random Number Generated by Functor" << std::endl;
  for (int val : randomNum)
      std::cout << val << std::endl; 

return 0;
}
